fix(storage-box): subaccount name was ignored
While the `storage_box_subaccount.name` was added in #1323, it was not
actually passed on to the API. This causes the following error in case
the user configured the field, as the API returned a different value:

    Error: Provider produced inconsistent result after apply

    When applying changes to hcloud_storage_box_subaccount.test, provider "provider[\"registry.opentofu.org/hetznercloud/hcloud\"]" produced an unexpected new value: .name: was
    cty.StringVal("badger"), but now cty.StringVal("u545557-sub1").

The field is now being passed to the API in "Create" and "Update", and
there is a test that verifies the functionality.

Closes #1333