test: fix flaky test TestServerResource_PrimaryIPNetworkTests
Test was flaky because two hcloud_primary_ip resources used the same name,
but name must be unique. Fixed using different names.

Error message:

    resource_test.go:520: Step 6/7 error: Error running apply: exit status 1

    Error: name is already used (uniqueness_error)

      with hcloud_primary_ip.primary-ip-v6,
      on terraform_plugin_test.tf line 21, in resource "hcloud_primary_ip" "primary-ip-v6":
      21: resource "hcloud_primary_ip" "primary-ip-v6" {

    --- FAIL: TestServerResource_PrimaryIPNetworkTests (123.13s)